-- Allows one person to be assigned to additional organizations.
-- Keep people.org_id as the primary organization, and store secondary
-- assignments here.

create table if not exists person_org_assignments (
  assignment_id bigint generated by default as identity primary key,
  person_id bigint not null references people(person_id) on delete cascade,
  org_id bigint not null references orgs(org_id) on delete cascade,
  created_at timestamp without time zone not null default now(),
  constraint uq_person_org_assignment unique (person_id, org_id)
);

create index if not exists idx_person_org_assignments_person
  on person_org_assignments(person_id);

create index if not exists idx_person_org_assignments_org
  on person_org_assignments(org_id);

grant select, insert, update, delete on person_org_assignments to anon, authenticated;
grant usage, select on sequence person_org_assignments_assignment_id_seq to anon, authenticated;

alter table person_org_assignments disable row level security;

notify pgrst, 'reload schema';
