-- Production RLS for ConnectCall Admin.
--
-- IMPORTANT:
-- This file is designed for production security with Supabase Auth JWTs.
-- The current React-only custom login that reads auth_users.pass_hash from the
-- browser is not compatible with strong RLS. Move login to Supabase Auth or a
-- SECURITY DEFINER RPC/Edge Function before enabling this in production.
--
-- Expected JWT role values:
--   app_metadata.role = 'admin' | 'manager' | 'readonly'
-- or user_metadata.role with the same values.

begin;

create extension if not exists pgcrypto;

-- Optional link between an auth user record and the person record it owns.
alter table auth_users
  add column if not exists person_id bigint references people(person_id);

update auth_users au
set person_id = p.person_id
from people p
where au.person_id is null
  and lower(trim(au.full_name)) = lower(trim(p.full_name));

create table if not exists person_org_assignments (
  assignment_id bigint generated by default as identity primary key,
  person_id bigint not null references people(person_id) on delete cascade,
  org_id bigint not null references orgs(org_id) on delete cascade,
  created_at timestamp without time zone not null default now(),
  constraint uq_person_org_assignment unique (person_id, org_id)
);

create index if not exists idx_person_org_assignments_person
  on person_org_assignments(person_id);

create index if not exists idx_person_org_assignments_org
  on person_org_assignments(org_id);

create or replace function public.app_jwt_role()
returns text
language sql
stable
as $$
  select coalesce(
    auth.jwt() -> 'app_metadata' ->> 'role',
    auth.jwt() -> 'user_metadata' ->> 'role',
    'readonly'
  );
$$;

create or replace function public.app_jwt_email()
returns text
language sql
stable
as $$
  select lower(coalesce(auth.jwt() ->> 'email', ''));
$$;

create or replace function public.app_user_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select au.user_id
  from auth_users au
  where lower(coalesce(au.email, '')) = public.app_jwt_email()
  limit 1;
$$;

create or replace function public.app_person_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select au.person_id
  from auth_users au
  where au.user_id = public.app_user_id()
  limit 1;
$$;

create or replace function public.app_is_admin()
returns boolean
language sql
stable
as $$
  select public.app_jwt_role() = 'admin';
$$;

create or replace function public.app_is_manager()
returns boolean
language sql
stable
as $$
  select public.app_jwt_role() = 'manager';
$$;

create or replace function public.app_can_manage()
returns boolean
language sql
stable
as $$
  select public.app_jwt_role() in ('admin', 'manager');
$$;

grant execute on function public.app_jwt_role() to authenticated;
grant execute on function public.app_jwt_email() to authenticated;
grant execute on function public.app_user_id() to authenticated;
grant execute on function public.app_person_id() to authenticated;
grant execute on function public.app_is_admin() to authenticated;
grant execute on function public.app_is_manager() to authenticated;
grant execute on function public.app_can_manage() to authenticated;

-- Lock down table privileges first.
revoke all on
  orgs,
  people,
  systems,
  accounts,
  account_kv,
  audit_log,
  auth_login_attempts,
  auth_users,
  auth_roles,
  inbox_messages,
  vault_secrets,
  person_org_assignments
from anon;

grant select on auth_roles to authenticated;
grant select, insert, update, delete on
  orgs,
  people,
  systems,
  accounts,
  account_kv,
  inbox_messages,
  person_org_assignments
to authenticated;

grant select, insert, update on auth_users to authenticated;
grant select, insert on audit_log to authenticated;
grant select, insert on auth_login_attempts to authenticated;
grant insert on auth_login_attempts to anon;
grant select, insert, update, delete on vault_secrets to authenticated;

grant usage, select on all sequences in schema public to authenticated;
grant usage, select on sequence auth_login_attempts_attempt_id_seq to anon;

alter table orgs enable row level security;
alter table people enable row level security;
alter table systems enable row level security;
alter table accounts enable row level security;
alter table account_kv enable row level security;
alter table audit_log enable row level security;
alter table auth_login_attempts enable row level security;
alter table auth_users enable row level security;
alter table auth_roles enable row level security;
alter table inbox_messages enable row level security;
alter table vault_secrets enable row level security;
alter table person_org_assignments enable row level security;

-- Drop known production policy names so the script can be rerun.
drop policy if exists "prod_orgs_select" on orgs;
drop policy if exists "prod_orgs_manage" on orgs;
drop policy if exists "prod_people_select" on people;
drop policy if exists "prod_people_manage" on people;
drop policy if exists "prod_systems_select" on systems;
drop policy if exists "prod_systems_manage" on systems;
drop policy if exists "prod_accounts_select" on accounts;
drop policy if exists "prod_accounts_manage" on accounts;
drop policy if exists "prod_account_kv_select" on account_kv;
drop policy if exists "prod_account_kv_manage" on account_kv;
drop policy if exists "prod_person_org_assignments_select" on person_org_assignments;
drop policy if exists "prod_person_org_assignments_manage" on person_org_assignments;
drop policy if exists "prod_inbox_select" on inbox_messages;
drop policy if exists "prod_inbox_insert" on inbox_messages;
drop policy if exists "prod_inbox_update" on inbox_messages;
drop policy if exists "prod_auth_roles_select" on auth_roles;
drop policy if exists "prod_auth_users_select" on auth_users;
drop policy if exists "prod_auth_users_update" on auth_users;
drop policy if exists "prod_auth_users_insert_admin" on auth_users;
drop policy if exists "prod_audit_log_select" on audit_log;
drop policy if exists "prod_audit_log_insert" on audit_log;
drop policy if exists "prod_login_attempts_select" on auth_login_attempts;
drop policy if exists "prod_login_attempts_insert_auth" on auth_login_attempts;
drop policy if exists "prod_login_attempts_insert_anon" on auth_login_attempts;
drop policy if exists "prod_vault_secrets_admin" on vault_secrets;

create policy "prod_orgs_select"
on orgs for select
to authenticated
using (
  public.app_can_manage()
  or org_id in (
    select p.org_id from people p where p.person_id = public.app_person_id()
    union
    select poa.org_id
    from person_org_assignments poa
    where poa.person_id = public.app_person_id()
  )
);

create policy "prod_orgs_manage"
on orgs for all
to authenticated
using (public.app_can_manage())
with check (public.app_can_manage());

create policy "prod_people_select"
on people for select
to authenticated
using (
  public.app_can_manage()
  or person_id = public.app_person_id()
);

create policy "prod_people_manage"
on people for all
to authenticated
using (public.app_can_manage())
with check (public.app_can_manage());

create policy "prod_systems_select"
on systems for select
to authenticated
using (public.app_can_manage());

create policy "prod_systems_manage"
on systems for all
to authenticated
using (public.app_can_manage())
with check (public.app_can_manage());

create policy "prod_accounts_select"
on accounts for select
to authenticated
using (
  public.app_can_manage()
  or person_id = public.app_person_id()
);

create policy "prod_accounts_manage"
on accounts for all
to authenticated
using (public.app_can_manage())
with check (public.app_can_manage());

create policy "prod_account_kv_select"
on account_kv for select
to authenticated
using (
  public.app_can_manage()
  or account_id in (
    select a.account_id
    from accounts a
    where a.person_id = public.app_person_id()
  )
);

create policy "prod_account_kv_manage"
on account_kv for all
to authenticated
using (public.app_can_manage())
with check (public.app_can_manage());

create policy "prod_person_org_assignments_select"
on person_org_assignments for select
to authenticated
using (
  public.app_can_manage()
  or person_id = public.app_person_id()
);

create policy "prod_person_org_assignments_manage"
on person_org_assignments for all
to authenticated
using (public.app_can_manage())
with check (public.app_can_manage());

create policy "prod_inbox_select"
on inbox_messages for select
to authenticated
using (
  public.app_can_manage()
  or sender_user_id = public.app_user_id()
);

create policy "prod_inbox_insert"
on inbox_messages for insert
to authenticated
with check (
  public.app_can_manage()
  or sender_user_id = public.app_user_id()
);

create policy "prod_inbox_update"
on inbox_messages for update
to authenticated
using (
  public.app_can_manage()
  or sender_user_id = public.app_user_id()
)
with check (
  public.app_can_manage()
  or sender_user_id = public.app_user_id()
);

create policy "prod_auth_roles_select"
on auth_roles for select
to authenticated
using (true);

create policy "prod_auth_users_select"
on auth_users for select
to authenticated
using (
  public.app_is_admin()
  or user_id = public.app_user_id()
);

create policy "prod_auth_users_update"
on auth_users for update
to authenticated
using (
  public.app_is_admin()
  or user_id = public.app_user_id()
)
with check (
  public.app_is_admin()
  or user_id = public.app_user_id()
);

create policy "prod_auth_users_insert_admin"
on auth_users for insert
to authenticated
with check (public.app_is_admin());

create policy "prod_audit_log_select"
on audit_log for select
to authenticated
using (public.app_can_manage());

create policy "prod_audit_log_insert"
on audit_log for insert
to authenticated
with check (true);

create policy "prod_login_attempts_select"
on auth_login_attempts for select
to authenticated
using (public.app_is_admin());

create policy "prod_login_attempts_insert_auth"
on auth_login_attempts for insert
to authenticated
with check (true);

create policy "prod_login_attempts_insert_anon"
on auth_login_attempts for insert
to anon
with check (true);

create policy "prod_vault_secrets_admin"
on vault_secrets for all
to authenticated
using (public.app_is_admin())
with check (public.app_is_admin());

notify pgrst, 'reload schema';

commit;
